export const dummyStudents = [
  {
    id: "S001",
    name: "Andi Pratama",
    class: "12-A",
    status: "active",
    averageScore: 88.5,
    activityLevel: 92,
    profile: {
      nisn: "0012345678",
      gender: "Laki-laki",
      dateOfBirth: "2006-05-15",
      address: "Jl. Merdeka No. 10, Bandung",
    },
  },
  {
    id: "S002",
    name: "Sari Dewi",
    class: "12-A",
    status: "active",
    averageScore: 91.2,
    activityLevel: 85,
    profile: {
      nisn: "0012345679",
      gender: "Perempuan",
      dateOfBirth: "2006-08-22",
      address: "Jl. Pahlawan No. 5, Bandung",
    },
  },
  {
    id: "S003",
    name: "Rian Hidayat",
    class: "11-B",
    status: "active",
    averageScore: 85.0,
    activityLevel: 95,
    profile: {
      nisn: "0023456780",
      gender: "Laki-laki",
      dateOfBirth: "2007-01-30",
      address: "Jl. Cendrawasih No. 15, Jakarta",
    },
  },
  {
    id: "S004",
    name: "Citra Lestari",
    class: "11-B",
    status: "inactive",
    averageScore: 78.3,
    activityLevel: 60,
    profile: {
      nisn: "0023456781",
      gender: "Perempuan",
      dateOfBirth: "2007-03-12",
      address: "Jl. Kenanga No. 20, Jakarta",
    },
  },
  {
    id: "S005",
    name: "Eko Nugroho",
    class: "10-C",
    status: "active",
    averageScore: 95.0,
    activityLevel: 98,
    profile: {
      nisn: "0034567890",
      gender: "Laki-laki",
      dateOfBirth: "2008-11-02",
      address: "Jl. Mawar No. 3, Surabaya",
    },
  },
];