export const dummyTeachers = [
  {
    id: "T001",
    name: "Budi Santoso",
    subject: "Matematika",
    classes: ["10-A", "10-B", "11-A"],
    teachingHours: 24,
    status: "Active",
  },
  {
    id: "T002",
    name: "Siti Aminah",
    subject: "Bahasa Indonesia",
    classes: ["10-A", "10-C", "12-B"],
    teachingHours: 22,
    status: "Active",
  },
  {
    id: "T003",
    name: "Agus Setiawan",
    subject: "Fisika",
    classes: ["11-A", "11-B", "12-A"],
    teachingHours: 20,
    status: "Active",
  },
  {
    id: "T004",
    name: "Dewi Lestari",
    subject: "Kimia",
    classes: ["11-C", "12-B", "12-C"],
    teachingHours: 21,
    status: "Non-Active",
  },
  {
    id: "T005",
    name: "Rahmat Hidayat",
    subject: "Biologi",
    classes: ["10-B", "11-B", "12-C"],
    teachingHours: 23,
    status: "Active",
  },
];